### ISSUE TITLE
how to run it?

### ISSUE THREAD

**Issue by zoldseges** [aengelke/mandel-qpu#1]

**Comment by zoldseges** [comment]
I might be stupid, but i couldn't figure out what arguments should I pass and what format

**Comment by aengelke** [comment]
There is a brief [usage instruction](https://github.com/aengelke/mandel-qpu/blob/master/qpu_mandel.c#L324) in the code (e.g., `./qpu_mandel -2 2 -1.125 1920 1080 100 4 out.netcdf` *should* work); the output format is NetCDF.
